### PR TITLE
Detect systemless root

### PR DESCRIPTION
**Pull request by d4rken**
`/su/bin` should only exist on rooted device.

### CODE REVIEW

**Comment by d4rken** [comment]
Merge #140 to fix the build issue.

**Comment by kattrali** [comment]
Thanks, @d4rken! I merged manually to pull out the unrelated changes, but this looks good. 👍

**Comment by d4rken** [comment]
@kattrali Are the other changes against the prefered code style or what's the issue with them? I made those on purpose (wasn't an auto formatter accident).

**Comment by kattrali** [comment]
@d4rken Ah, gotcha. I assumed it was from a formatter. From a maintenance perspective, its hard to look back through commits when a single change can have different purposes. I spend a fair amount of time looking back through rationale for decisions in git history, so generally try to not mix formatting changes in with hot fixes. Outside of that,the changes were a bit different from the existing style, so I the purpose of the change wasn't obvious during review.

**Pull request closed without merging**
