### PR TITLE
Fix NPE when unboxing in JsonStream

### PR DESCRIPTION
**Pull request by mattprecious**

### CODE REVIEW

**Comment by mattprecious** [comment]
Uhh... I think this one needs to be merged and released ASAP. I believe no crashes are being reported pre-5.0 without the `GET_TASKS` permission since `isInForeground()` returns `null`.

**Comment by ConradIrwin** [comment]
Thanks @mattprecious, @JakeWharton!

**Comment by loopj** [comment]
Released as v3.2.1, propagating through maven central now. Thanks again!

**Comment by mattprecious** [comment]
Thanks for the quick release!

**Pull request merged**
