### PR TITLE
Enable test coverage with jacoco

### PR DESCRIPTION
**Pull request by fractalwrench**
Adds the `createDebugCoverageReport` task, which generates a Jacoco report under the build folder when run.

### CODE REVIEW

**Comment by kattrali** [comment]
Is there a way we can surface this during CI, or some service we can use for this? Though without checking I'm sure coveralls has some extension for Java/jacoco.

**Comment by fractalwrench** [comment]
Codecov is one option: https://github.com/codecov/example-android

**Comment by kattrali** [comment]
There is this: https://github.com/kt3k/coveralls-gradle-plugin

and we are already using coveralls on other platforms

**Comment by kattrali** [comment]
Updated to get reports. [Here's an example](https://coveralls.io/builds/15171443)

**Pull request merged**
