### PR TITLE
update the gradle-wrapper from 2.2 to 2.10

### PR DESCRIPTION
**Pull request by larsgrefer**

### CODE REVIEW

**Comment by JakeWharton** [comment]
2.10 is latest

**Comment by larsgrefer** [comment]
@JakeWharton Thanks for the info, i'll update the PR

**Comment by JakeWharton** [comment]
I just built this project locally for the first time in about a year. The
2.2 surprised me too, but I forgot to make a PR for it. So thanks!

**Comment by larsgrefer** [comment]
2.10 won't work until #88 is merged

**Comment by kattrali** [comment]
This also looks good. Thanks again, @larsgrefer.

**Pull request merged**
