### PR TITLE
Update example app and test fixture dependencies

### PR DESCRIPTION
**Pull request by fractalwrench**
## Goal

Updates the example app and test fixtures to use the latest AGP version (4.0.0), and updates their dependencies to ensure they are not left abandoned on an obsolete version.

This is part of the groundwork of preparing the entire project to use AGP 4.0.0.

## Changeset

- Updated android sizer task to use 1.0.0 of bundletool
- Updated apps to use latest compileSdkVersion of 29, AGP 4.0.0, Kotlin 1.3.72
- Added one Java file to `minimalapp` fixture to prevent Android Bundle failing to generate APKs with AGP 4.0.0 due to no code being present
- Removed unneeded test dependencies from minimalapp
- Updated android sizer script to get APKs/AABs from new generated location
- Updated test fixture to allow clear text traffic required by bs-local.com, which was failing the scenarios on Android 9 after upgrading the compileSdkVersion

### CODE REVIEW

**Comment by tomlongridge** [comment]
This now seems to preclude the use of Android Studio < 4.0:

> This version of Android Studio cannot open this project, please retry with Android Studio 4.0 or newer.

**Comment by fractalwrench** [comment]
Android Studio 4 only officially supports AGP 4, so I believe we'll ultimately need to upgrade the plugin in the example app and choose which Android Studio versions we care about more. I'd be inclined to bump it as we're using pretty ancient versions as it stands.

**Comment by tomlongridge** [comment]
> Android Studio 4 only officially supports AGP 4, so I believe we'll ultimately need to upgrade the plugin in the example app and choose which Android Studio versions we care about more. I'd be inclined to bump it as we're using pretty ancient versions as it stands.

Android Studio 4.0 is not old (it was released in May), so we need to find a way to be able to still run our example in 3.x.

**Comment by fractalwrench** [comment]
Updated as per review feedback

**Comment by fractalwrench** [comment]
Using 3.6.0 for the example app _should_ work but it's unsupported by Android Studio and is subject to breaking/showing a warning message in future versions of Android Studio. Android Studio 4.0 is reasonably old in Android terms as it's very common to use the beta channel or canary channel.

**Comment by fractalwrench** [comment]
Downgraded AGP to 3.6.0 for the example app only.

**Pull request merged**
