### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by friederbluemle**
- Gradle wrapper `4.0.2`
- Android Gradle plugin `2.3.3`
- build tools `25.0.3`

<sub><sup>Please NO GitHub rebase/squash merges. If you'd like me to combine some or all of the commits, please let me know, and I will update my branch. Thank you.</sup></sub>

### CODE REVIEW

**Comment by friederbluemle** [comment]
Fixed conflicts and updated to latest versions.

**Comment by friederbluemle** [comment]
Rebased and updated to the latest versions.

**Comment by friederbluemle** [comment]
Updated again to latest stable Gradle wrapper version `4.0.1` and rebased.

**Comment by friederbluemle** [comment]
@fractalwrench Rebased and force pushed my branch. It only contains two commits on top of `master` now.

**Comment by friederbluemle** [comment]
The build is green as well now (finally)! Thanks for fixing it in one of the previous commits! 👍

**Comment by fractalwrench** [comment]
@kattrali this looks good to me (minus the example/build.gradle conflict) - can you spot anything I might have missed?

**Comment by friederbluemle** [comment]
@fractalwrench @kattrali Rebased onto latest `master`, fixed conflict, and force pushed to my branch.

**Comment by kattrali** [comment]
All good, thanks again, @friederbluemle!

**Pull request merged**
