### PR TITLE
Add performance benchmark tests

### PR DESCRIPTION
**Pull request by fractalwrench**
## Goal

Adds performance tests using the [microbenchmark library](https://developer.android.com/studio/profile/benchmark) which provide a baseline insight into Bugsnag's performance.

These tests focus primarily on Bugsnag's critical path (notify/metadata/breadcrumbs) but has added some additional test cases to measure some other APIs - although this is not exhaustive.

I've avoided benchmarking `Bugsnag.start()` as this led to OOMs - the macrobenchmark library may be a better fit for this, which will be investigated separately.

## Changeset

Added benchmark tests for the following:

- Starting/pausing/resuming sessions
- Creating an `Event`
- Setting the user and context
- Constructing `Configuration`
- Calling `Bugsng.notify()`
- Leaving breadcrumbs on the client
- Leaving metadata on the client

### CODE REVIEW

**Review by lemnik — APPROVED** [review]
LGTM

**Comment by lemnik** [comment]
It would be good to add a benchmark covering the JSON serialization for a typical event / session payload.

**Comment by fractalwrench** [comment]
Updated to include benchmarks for JSON serialization.

**Review by lemnik — APPROVED** [review]
LGTM

**Pull request merged**
